- name: Prepare packaging variables
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "{{ release_type }}"

- name: get a list of package files
  find:
    paths: "{{ zuul.executor.work_root }}/packages/"
    recurse: yes
    patterns:
      - '*.rpm'
  register: package_list
  delegate_to: localhost

- name: check if directory contains packages to upload
  meta: end_play
  when: package_list.matched|int == 0

- name: upload packages to pulp server
  synchronize:
    src: "{{ executor_package_dir }}"
    dest: /root/{{ packaging.repo_name }}

- name: delete repo
  command: pulp-admin rpm repo delete --repo-id {{ packaging.repo_name }}

- name: create repo
  command: pulp-admin rpm repo create --repo-id {{ packaging.repo_name }} --serve-http true

- name: add packages to pulp
  command: pulp-admin rpm repo uploads rpm --repo-id {{ packaging.repo_name }} --dir /root/{{ packaging.repo_name }}/packages

- name: publish repo
  command: pulp-admin rpm repo publish run --repo-id {{ packaging.repo_name }}

- name: remove package directory from pulp server
  file:
    path: /root/{{ packaging.repo_name }}
    state: absent

- name: Return repository location back to zuul for children jobs
  zuul_return:
    data:
      contrail_package_repository: "http://{{ site_pulp.fqdn }}/pulp/repos/{{ packaging.repo_name }}"
  delegate_to: localhost

